### ISSUE TITLE
Поверніть мені тон

### ISSUE THREAD

**Issue by Tok-tal** [ton-blockchain/highload-wallet-contract-v3#13]
Помилково надіслала вам . 
Ось мій гаманець UQD6BIk808z0g0Zk2KxzE5r8Ad3Aa8R2xgJ_3RciQ1uQmEZB
Поверніть будь ласка!
![Screenshot_20240926-183945](https://github.com/user-attachments/assets/6fe83b11-da12-4a3c-82d2-d5c0cbba1100)

**Comment by Shurup1987com** [comment]
Ти вмієш писати код для блокчейну тон https://github.com/ton-blockchain/highload-wallet-contract-v3

**Comment by Shurup1987com** [comment]
Я тобі заплачу
